# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Girke Lab
tagline:             'Research and Teaching Site'
description:         '[Thomas Girke](thomas-girke)'
url:                 https://tgirke.github.io
baseurl:             ''
# The following line is required for Jekyll >=3 support
gems:                [jekyll-paginate, jekyll-gist]
paginate:            5

# About/contact
author:
  name:              Thomas Girke
  url:               https://girke.bioinformatics.ucr.edu
  email:             thomas.girke@ucr.edu

# Custom vars
version:             Lanyon
